server:
  port: 9081

spring:
  h2:
    console:
      enabled: true
      path: /db
  datasource:
    url: jdbc:h2:mem:tododb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect